export const PanopticFactoryV4Abi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_SFPM', type: 'address', internalType: 'contract SemiFungiblePositionManagerV4' },
      { name: '_manager', type: 'address', internalType: 'contract IPoolManager' },
      { name: '_poolReference', type: 'address', internalType: 'address' },
      { name: '_collateralReference', type: 'address', internalType: 'address' },
      { name: 'properties', type: 'bytes32[]', internalType: 'bytes32[]' },
      { name: 'indices', type: 'uint256[][]', internalType: 'uint256[][]' },
      { name: 'pointers', type: 'uint256[][]', internalType: 'Pointer[][]' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'spender', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'constructMetadata',
    inputs: [
      { name: 'panopticPool', type: 'address', internalType: 'address' },
      { name: 'symbol0', type: 'string', internalType: 'string' },
      { name: 'symbol1', type: 'string', internalType: 'string' },
      { name: 'fee', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deployNewPool',
    inputs: [
      {
        name: 'key',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
      { name: 'riskEngine', type: 'address', internalType: 'contract IRiskEngine' },
      { name: 'salt', type: 'uint96', internalType: 'uint96' },
    ],
    outputs: [
      { name: 'newPoolContract', type: 'address', internalType: 'contract PanopticPoolV2' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getApproved',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPanopticPool',
    inputs: [
      {
        name: 'keyV4',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
      { name: 'riskEngine', type: 'address', internalType: 'contract IRiskEngine' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'contract PanopticPoolV2' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minePoolAddress',
    inputs: [
      { name: 'deployerAddress', type: 'address', internalType: 'address' },
      {
        name: 'key',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
      { name: 'riskEngine', type: 'address', internalType: 'address' },
      { name: 'salt', type: 'uint96', internalType: 'uint96' },
      { name: 'loops', type: 'uint256', internalType: 'uint256' },
      { name: 'minTargetRarity', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'bestSalt', type: 'uint96', internalType: 'uint96' },
      { name: 'highestRarity', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'id', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    inputs: [
      { name: 'operator', type: 'address', internalType: 'address' },
      { name: 'approved', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    name: 'Approval',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address', indexed: true },
      { name: 'spender', type: 'address', internalType: 'address', indexed: true },
      { name: 'id', type: 'uint256', internalType: 'uint256', indexed: true },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'ApprovalForAll',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address', indexed: true },
      { name: 'operator', type: 'address', internalType: 'address', indexed: true },
      { name: 'approved', type: 'bool', internalType: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'PoolDeployed',
    inputs: [
      {
        name: 'poolAddress',
        type: 'address',
        internalType: 'contract PanopticPoolV2',
        indexed: true,
      },
      { name: 'idV4', type: 'bytes32', internalType: 'PoolId', indexed: true },
      {
        name: 'collateralTracker0',
        type: 'address',
        internalType: 'contract CollateralTrackerV2',
        indexed: false,
      },
      {
        name: 'collateralTracker1',
        type: 'address',
        internalType: 'contract CollateralTrackerV2',
        indexed: false,
      },
      { name: 'riskEngine', type: 'address', internalType: 'contract IRiskEngine', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'Transfer',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address', indexed: true },
      { name: 'to', type: 'address', internalType: 'address', indexed: true },
      { name: 'id', type: 'uint256', internalType: 'uint256', indexed: true },
    ],
  },
  { type: 'error', name: 'AlreadyInitialized', inputs: [] },
  { type: 'error', name: 'CreateFail', inputs: [] },
  { type: 'error', name: 'PoolNotInitialized', inputs: [] },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
] as const
