export const PanopticVaultAccountantAbi = [
  {
    type: 'constructor',
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: '_wethAddress', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'error', name: 'CastingError', inputs: [] },
  { type: 'error', name: 'DuplicateERC4626', inputs: [] },
  { type: 'error', name: 'DuplicatePool', inputs: [] },
  { type: 'error', name: 'ERC4626UnderlyingMismatch', inputs: [] },
  { type: 'error', name: 'IncorrectPositionList', inputs: [] },
  { type: 'error', name: 'InvalidERC4626Vaults', inputs: [] },
  { type: 'error', name: 'InvalidPools', inputs: [] },
  { type: 'error', name: 'InvalidTick', inputs: [] },
  { type: 'error', name: 'LiquidityTooHigh', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
  },
  { type: 'error', name: 'StaleOraclePrice', inputs: [] },
  { type: 'error', name: 'UnderOverFlow', inputs: [] },
  { type: 'error', name: 'VaultLocked', inputs: [] },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
  },
  {
    type: 'function',
    name: 'computeNAV',
    inputs: [
      { internalType: 'address', name: 'vault', type: 'address' },
      { internalType: 'address', name: 'underlyingToken', type: 'address' },
      { internalType: 'bytes', name: 'managerInput', type: 'bytes' },
    ],
    outputs: [{ internalType: 'uint256', name: 'nav', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lockVault',
    inputs: [{ internalType: 'address', name: 'vault', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateHashes',
    inputs: [
      { internalType: 'address', name: 'vault', type: 'address' },
      {
        internalType: 'struct PanopticVaultAccountant.PoolInfo[]',
        name: 'pools',
        type: 'tuple[]',
        components: [
          { internalType: 'contract PanopticPoolV2', name: 'pool', type: 'address' },
          { internalType: 'contract IERC20Partial', name: 'token0', type: 'address' },
          { internalType: 'contract IERC20Partial', name: 'token1', type: 'address' },
          { internalType: 'int24', name: 'maxPriceDeviation', type: 'int24' },
        ],
      },
      {
        internalType: 'contract IERC4626[]',
        name: 'erc4626Vaults',
        type: 'address[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'vaultHashes',
    inputs: [
      { internalType: 'address', name: 'vault', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    outputs: [{ internalType: 'bytes32', name: 'hashes', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vaultLocked',
    inputs: [{ internalType: 'address', name: 'vault', type: 'address' }],
    outputs: [{ internalType: 'bool', name: 'isLocked', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'wethAddress',
    inputs: [],
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
  },
] as const
