/**
 * Public React entry for the Panoptic v2 SDK: `@panoptic-eng/sdk/v2/react`.
 *
 * This is a SUPERSET of `@panoptic-eng/sdk/v2` — it re-exports the entire pure
 * `/v2` surface AND the React hooks / provider / query utilities. Import from
 * here in React apps; import from `@panoptic-eng/sdk/v2` in bots/servers that
 * must stay React-free (the base `/v2` barrel intentionally pulls in no React).
 * @module v2/react
 */

// Pure, React-free v2 surface (reads, writes, tokenId, sync, formatters, …).
export * from './index'

// ============================================================================
// React Integration
export type {
  MutationEffectParams,
  MutationType,
  PanopticContextValue,
  PanopticProviderProps,
  PriceHistoryTimeRange,
  QueryOptions,
} from './react'
export {
  isCowSupportedChain,
  mutationEffects,
  PanopticProvider,
  queryKeys,
  // Hooks — reads
  useAccountCollateral,
  useAccountGreeks,
  useAccountPremia,
  useAccountSummaryBasic,
  useAccountSummaryRisk,
  // Hooks — sync
  useAddPendingPosition,
  // Hooks — writes
  useApprove,
  // Hooks — swaps
  useApproveErc20ForCow,
  useApproveErc20ForPermit2,
  useApprovePool,
  useApproveRouterViaPermit2,
  useBatchDispatch as useBatchDispatchHook,
  useBorrow as useBorrowHook,
  useCancelCowOrder,
  useCheckCowApproval,
  useCheckRouterApproval,
  useChunkSpreads,
  useClearTrackedPositions,
  useClosedPositions,
  useClosePosition as useClosePositionHook,
  useCollateralData,
  useConfirmPendingPosition,
  useCowOrderStatus,
  useCurrentRates,
  useDeployNewPool as useDeployNewPoolHook,
  useDeposit as useDepositHook,
  useDispatch as useDispatchHook,
  useEstimateCollateralRequired,
  // Hooks — events
  useEventPoller,
  useEventSubscription,
  useFactoryConstructMetadata,
  useFactoryOwnerOf,
  useFactoryTokenURI,
  useFailPendingPosition,
  useFlowNeutralTokenId,
  useForceExercise as useForceExerciseHook,
  useGuardianUnlockState,
  useInterestState,
  useIsLiquidatable,
  useLiquidate as useLiquidateHook,
  useLiquidationPrices,
  useMarginBuffer,
  useMaxPositionSize,
  useMaxWithdrawable,
  useMinePoolAddress as useMinePoolAddressHook,
  useMintShares,
  useNativeTokenPrice,
  useNetLiquidationValue,
  useNetLiquidationValues,
  useOpenPosition as useOpenPositionHook,
  useOpenPositionPreview,
  useOptimizeRiskPartners,
  useOracleState,
  usePanopticContext,
  usePanopticPoolAddress,
  usePokeOracle as usePokeOracleHook,
  usePool,
  usePoolLiquidities,
  usePosition,
  usePositionGreeks,
  usePositions,
  usePositionsWithPremia,
  usePreviewBorrow,
  usePreviewDeposit,
  usePreviewMint,
  usePreviewRedeem,
  usePreviewWithdraw,
  usePriceHistory,
  useQuoteCowSwap,
  useQuoteSwapExactInViaRouter,
  useQuoteSwapExactOutViaRouter,
  useRealizedPnL,
  useRedeem as useRedeemHook,
  useRepay as useRepayHook,
  useResolveUniswapV4PoolKey,
  useRiskParameters,
  useRollPosition as useRollPositionHook,
  useSafeMode,
  useSettleAccumulatedPremia as useSettleAccumulatedPremiaHook,
  // Hooks — simulations
  useSimulateBatchDispatch,
  useSimulateClosePosition,
  useSimulateDeployNewPool,
  useSimulateDeposit,
  useSimulateDispatch,
  useSimulateForceExercise,
  useSimulateLiquidate,
  useSimulateOpenPosition,
  useSimulateSettle,
  useSimulateSFPMBurn,
  useSimulateSFPMMint,
  useSimulateSwapExactIn,
  useSimulateSwapExactOut,
  useSimulateWithdraw,
  useSmartRepay as useSmartRepayHook,
  useStreamiaHistory,
  useSubmitCowOrder,
  useSupply as useSupplyHook,
  useSwapExactIn,
  useSwapExactInViaRouter,
  useSwapExactOut,
  useSwapExactOutViaRouter,
  useSyncPositions,
  useSyncStatus,
  useTrackedPositionIds,
  useTradeHistory,
  useTxEventConfirmation,
  useUniswapFeeHistory,
  useUniswapV3PoolInfo,
  useUniswapV3PoolLiquidities,
  useUniswapV4PoolBasicState,
  useUniswapV4PoolInfo,
  useUniswapV4PoolLiquidities,
  useUnsupply as useUnsupplyHook,
  useUnwrapWeth,
  useUnwrapXstock,
  useUtilization,
  useValidateBuilderCode,
  useWatchEvents,
  useWithdraw as useWithdrawHook,
  useWithdrawWithPositions as useWithdrawWithPositionsHook,
  useWrapEth,
  useWrapXstock,
} from './react'
